version: 0.2
phases:
  pre_build:
    commands:
      - echo "1. pre build step"
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 666402361323.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo "2. Build step"
      - docker build -f ./deploy-helper/nginx/Dockerfile.nginx -t nginx .
      - docker build -f Dockerfile -t php-fpm .
  post_build:
    commands:
      - echo 3. "Post build"
      - docker tag nginx:latest 666402361323.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest
      - docker push 666402361323.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:latest
      - docker tag php-fpm:latest 666402361323.dkr.ecr.ap-southeast-1.amazonaws.com/php-fpm:latest
      - docker push 666402361323.dkr.ecr.ap-southeast-1.amazonaws.com/php-fpm:latest

artifacts:
  files:
    - README.md
    - imagedefinitions.json