version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - 8082:80
    depends_on:
      - php-fpm

    volumes:
      - ./storage/log:/var/log/nginx
      - ./public:/var/www/public
      - ./deploy-helper/nginx:/etc/nginx/helper

    command: /bin/bash -c "sh /etc/nginx/helper/gen_nginx.sh && nginx -g 'daemon off;'"

    # networks:
    #   - web-net

    environment:
      - NGINX_HOST=server-web
      - NGINX_PORT=80

  php-fpm:
    container_name: server-web
    build:
      context: .
      dockerfile: ./deploy-helper/dev/Dockerfile

    working_dir: /var/www/

    # First run with seed
    command: /bin/sh -c "
      chmod -R 777 /var/www/storage
      && php artisan migrate
      && php artisan db:seed --class=DatabaseSeeder
      && php-fpm"

    # After first run
    # command: /bin/sh -c "chmod -R 777 /var/www/storage && php-fpm"

    volumes:
      - ./:/var/www

    depends_on:
      - dbstop 

    environment:
      - APP_KEY=base64:0/vsZK0O/cgGHM7mCFM8XfXMBuKzJkbPiZ74urwK5/g=
      - APP_DEBUG=true
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=taskassign
      - DB_USERNAME=root
      - DB_PASSWORD=12345678

  # In the first time initialize DB can take time (around 30s-1min, please check log)
  db:
    image: mariadb
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    # volumes: 
    #   - ~/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taskassign
      MYSQL_ROOT_PASSWORD: 12345678
      # MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    ports:
      - 8081:8080

